# Document:
# http://simiki.org/docs/configuration.html

url: https://worldmystery.org
title: WorldMystery
keywords: Unsolved mysteries, Supernatural power, Occult
description: This site aims to include cases of unsolved mysteries around the world,include:human mystery,celebrity mystery,mystery of military war,mystery of ancient civilization,archeological mystery,mystery of history and geography,animal and plant mystery,mystery of nature and science,mystery of the universe.
author: WorldMystery

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

default_ext: md
pygments: false
debug: false